# Generated by Django 3.1.7 on 2024-07-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder_app', '0004_auto_20240725_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspectphoto',
            name='photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
