# Generated by Django 3.1.7 on 2024-08-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder_app', '0007_auto_20240726_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspect',
            name='where',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
