# Generated by Django 3.1.7 on 2024-08-06 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finder_app', '0008_suspect_where'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspectphoto',
            name='suspect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_details', to='finder_app.suspect'),
        ),
    ]
