# Generated by Django 3.1.7 on 2024-08-27 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finder_app', '0009_auto_20240806_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('national_id', models.CharField(max_length=14, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='contact_photos/')),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(max_length=1)),
                ('status', models.CharField(max_length=255)),
                ('status_last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_of_father', to='finder_app.contact')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_of_mother', to='finder_app.contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finder_app.contact')),
            ],
        ),
        migrations.RemoveField(
            model_name='suspectphoto',
            name='suspect',
        ),
        migrations.DeleteModel(
            name='Suspect',
        ),
        migrations.DeleteModel(
            name='SuspectPhoto',
        ),
    ]
